/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EcuadionesLineales;

import java.text.DecimalFormat;  
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class Fact_LU extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Object[][] tableData2;
    public SistemasdeEcuaciones resolver3;
    public SistemasdeEcuaciones resolver2;
    
    public Fact_LU() {
       
        initComponents();
        
        
        DefaultTableModel model = new DefaultTableModel(0,0);
        
        
        
    
        
        matriz3.getTableHeader().setVisible(false);
        matriz3.setShowVerticalLines(true);
        matriz3.setShowHorizontalLines(true);
        matriz3.setModel(model);
        b3.getTableHeader().setVisible(false);
        b3.setShowHorizontalLines(true);
        b3.setModel(model);
        
        L3.getTableHeader().setVisible(false);
        L3.setShowVerticalLines(true);
        L3.setShowHorizontalLines(true);
        L3.setModel(model);
        
        U3.getTableHeader().setVisible(false);
        U3.setShowVerticalLines(true);
        U3.setShowHorizontalLines(true);
        U3.setModel(model);
        
        matriz4.getTableHeader().setVisible(false);
        matriz4.setShowVerticalLines(true);
        matriz4.setShowHorizontalLines(true);
        matriz4.setModel(model);
        Lb3.getTableHeader().setVisible(false);
        Lb3.setShowHorizontalLines(true);
        Lb3.setModel(model);
        
        matriz5.getTableHeader().setVisible(false);
        matriz5.setShowVerticalLines(true);
        matriz5.setShowHorizontalLines(true);
        matriz5.setModel(model);
        Ub3.getTableHeader().setVisible(false);
        Ub3.setShowHorizontalLines(true);
        Ub3.setModel(model);
        
        
        
        
        
        
   
    }
    void convertToFloat(Object[][] matriz,float[][] L){
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aplicacion1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        matriz3 = new javax.swing.JTable();
        rango3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        agregarMatriz3 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        matriz4 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        matriz5 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pasoMatriz1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        b31 = new javax.swing.JScrollPane();
        Lb3 = new javax.swing.JTable();
        b32 = new javax.swing.JScrollPane();
        Ub3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        b3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        L3 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        U3 = new javax.swing.JTable();
        LU3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        resultadoU = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        resultadoU1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Aplicacion 1"); // NOI18N

        matriz3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(matriz3);

        rango3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        rango3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rango3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tamaño");

        agregarMatriz3.setText("Crear Matriz");
        agregarMatriz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMatriz3ActionPerformed(evt);
            }
        });

        matriz4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(matriz4);

        matriz5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(matriz5);

        jLabel10.setText("L");

        jLabel11.setText("U");

        pasoMatriz1.setText("Mostrar solucion");
        pasoMatriz1.setActionCommand("Mostrar Solucion");
        pasoMatriz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasoMatriz1ActionPerformed(evt);
            }
        });

        jLabel13.setText("=");

        Lb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        b31.setViewportView(Lb3);

        Ub3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        b32.setViewportView(Ub3);

        jLabel14.setText("=");

        b3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane13.setViewportView(b3);

        jLabel17.setText("=");

        L3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane16.setViewportView(L3);

        U3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane17.setViewportView(U3);

        LU3.setText("Calcular LU");
        LU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LU3ActionPerformed(evt);
            }
        });

        jLabel20.setText("L");

        jLabel21.setText("U");

        jLabel22.setText("b");

        jLabel23.setText("b");

        jLabel24.setText("b");

        resultadoU.setColumns(20);
        resultadoU.setRows(5);
        jScrollPane19.setViewportView(resultadoU);

        resultadoU1.setColumns(20);
        resultadoU1.setRows(5);
        jScrollPane25.setViewportView(resultadoU1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(213, 213, 213)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rango3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(agregarMatriz3))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(LU3)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(pasoMatriz1)
                        .addGap(583, 583, 583))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rango3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addComponent(agregarMatriz3))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel17)))
                .addGap(10, 10, 10)
                .addComponent(LU3)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel14))
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel23))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel13))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                        .addComponent(b31, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))))))
                .addGap(47, 47, 47)
                .addComponent(pasoMatriz1)
                .addGap(94, 94, 94))
        );

        aplicacion1.addTab("LU", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(aplicacion1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(aplicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        aplicacion1.getAccessibleContext().setAccessibleName("Aplicacion 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMatriz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMatriz1ActionPerformed
        

    }//GEN-LAST:event_agregarMatriz1ActionPerformed

    private void rango1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void LU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LU3ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) matriz3.getModel();

        DefaultTableModel b3table = (DefaultTableModel) b3.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        DefaultTableModel dtm2 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm3 =  new DefaultTableModel(nRow,nCol);
        float[][] tabla3 = new float[nRow][nCol];
        float[] b3 = new float[nRow];

        for (int i = 0 ; i < nRow ; i++){
            for (int j = 0 ; j < nCol ; j++){

                tabla3[i][j] = Float.parseFloat(dtm.getValueAt(i,j).toString());
            }
        }
        for(int t = 0; t <nRow;t++){
            b3[t] = Float.parseFloat(b3table.getValueAt(t,0).toString());
        }
        resolver3 = new SistemasdeEcuaciones(Integer.parseInt(rango3.getSelectedItem().toString()),tabla3,b3);
        float [][] MatrizU = resolver3.matrizU();
        float [][] MatrizL = resolver3.L;

        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                float f =MatrizL[i][j];
                String k = Float.toString(f);
                dtm2.setValueAt(k,i,j);
            }
        }
        L3.setModel(dtm2);

        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                float f =MatrizU[i][j];
                String k = Float.toString(f);
                dtm3.setValueAt(k,i,j);
            }
        }
        U3.setModel(dtm3);

    }//GEN-LAST:event_LU3ActionPerformed

    private void pasoMatriz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasoMatriz1ActionPerformed
        float [] vector1 = resolver3.vector;
        String [][] sistemaL = resolver3.AcomodarSistemaL(resolver3.L);
        DefaultTableModel dtm = (DefaultTableModel) matriz3.getModel();

        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        DefaultTableModel dtm2 = new DefaultTableModel(nRow,nCol);
        DefaultTableModel dtm3 =  new DefaultTableModel(nRow,nCol);
        DefaultTableModel bLmodel = new DefaultTableModel(nRow,1);
        DefaultTableModel bUmodel =  new DefaultTableModel(nRow,1);

        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm2.setValueAt(sistemaL[i][j],i,j);
            }
        }
        matriz4.setModel(dtm2);
        for(int i=0;i<nRow;i++){
            bLmodel.setValueAt(Float.toString(vector1[i]), i, 0);
        }
        Lb3.setModel(bLmodel);

        float [] vector2 = resolver3.vector;
        float [] solucionL = resolver3.ResolversistemaL(resolver3.L, vector2);
        String h ="";
        if(nRow == 2){

            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";

        }
        if(nRow == 3){
            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";
            h+="y3 = "+solucionL[2]+" \n";

        }

        if(nRow == 4){
            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";
            h+="y3 = "+solucionL[2]+" \n";
            h+="y4 = "+solucionL[3]+" \n";

        }
        if(nRow == 5){
            h+="y1 = "+solucionL[0]+" \n";
            h+="y2 = "+solucionL[1]+" \n";
            h+="y3 = "+solucionL[2]+" \n";
            h+="y4 = "+solucionL[3]+" \n";
            h+="y5 = "+solucionL[4]+" \n";

        }
        resultadoU1.setText(h);

        String[][] sistemaU = resolver3.AcomodarSistemaU(resolver3.U);
        resolver3.mostrarSistemaU(sistemaU,solucionL);
        float[] solucionU = resolver3.ResolverSistemaU(resolver3.U, solucionL);

        for(int i =0; i< nRow; i++){
            for (int j=0; j < nCol;j++){
                dtm3.setValueAt(sistemaU[i][j],i,j);
            }
        }
        matriz5.setModel(dtm3);
        for(int i=0;i<nRow;i++){
            bUmodel.setValueAt(Float.toString(solucionU[i]), i, 0);
        }
        Ub3.setModel(bUmodel);

        h ="";
        if(nRow == 2){

            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";

        }
        if(nRow == 3){
            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";
            h+="x3 = "+solucionU[2]+" \n";

        }
        if(nRow == 4){
            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";
            h+="x3 = "+solucionU[2]+" \n";
            h+="x4 = "+solucionU[3]+" \n";

        }
        if(nRow == 5){
            h+="x1 = "+solucionU[0]+" \n";
            h+="x2 = "+solucionU[1]+" \n";
            h+="x3 = "+solucionU[2]+" \n";
            h+="x4 = "+solucionU[3]+" \n";
            h+="x5 = "+solucionU[4]+" \n";

        }
        resultadoU.setText(h);

    }//GEN-LAST:event_pasoMatriz1ActionPerformed

    private void agregarMatriz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMatriz3ActionPerformed
        int rango = Integer.valueOf((String)rango3.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel(rango,rango);
        matriz3.setModel(model);
        model = new DefaultTableModel(rango,1);
        b3.setModel(model);

    }//GEN-LAST:event_agregarMatriz3ActionPerformed

    private void rango3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rango3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rango3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fact_LU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fact_LU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fact_LU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fact_LU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Fact_LU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable L3;
    private javax.swing.JButton LU3;
    private javax.swing.JTable Lb3;
    private javax.swing.JTable U3;
    private javax.swing.JTable Ub3;
    private javax.swing.JButton agregarMatriz3;
    private javax.swing.JTabbedPane aplicacion1;
    private javax.swing.JTable b3;
    private javax.swing.JScrollPane b31;
    private javax.swing.JScrollPane b32;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable matriz3;
    private javax.swing.JTable matriz4;
    private javax.swing.JTable matriz5;
    private javax.swing.JButton pasoMatriz1;
    private javax.swing.JComboBox rango3;
    private javax.swing.JTextArea resultadoU;
    private javax.swing.JTextArea resultadoU1;
    // End of variables declaration//GEN-END:variables
}
